### ISSUE TITLE
Detection Ineffective on MNIST model 

### ISSUE THREAD

**Issue by ChengFu0118** [bolunwang/backdoor#1]
Dear Bolun,
Thanks so much for sharing your code.

I trained a trojaned and a cleaned MNIST model based on the settings of BadNet paper. I have tested the **attacked trojan accuracy** and **regular test accuracy** both larger than 98%. However, when I tried to detect the trojan using the code, the computed anomaly index for the trojaned model is 2.6 and for the cleaned model is 3.6.  I am wondering if you have any ideas about what might be the possible cause.

**Comment by bolunwang** [comment]
Thanks for your interest. I can't give much feedback given the lack of info here. Feel free to drop us an email with more detailed configuration of your experiment, like what's your trigger? What's the configuration for reverse engineering?

**Comment by ChengFu0118** [comment]
Thanks for the author, this issue has been resolved offline. There is a configuration error in my code.

**Comment by bolunwang** [comment]
Just a note for future reference. The problem was the inconsistent configuration of `INTENSITY_RANGE` during backdoor injection and reverse engineering. This parameter should be set to the same in both processes.
