### ISSUE TITLE
y_true and y_pred position

### ISSUE THREAD

**Issue by shihongf** [bolunwang/backdoor#11]
Hi, I'm curious that why the position of y_true and y_pred get exchange?  Is this a mistake or it is done on purpose? Can you please explain why? Thanks!
https://github.com/bolunwang/backdoor/blob/e8577747d4670366a02db3818bf60f978d4c6421/visualizer.py#L233

**Comment by Shawn-Shan** [comment]
I believe the result should be identical. You can print out the two values and make sure they are the same.

**Comment by shihongf** [comment]
Thanks for answering. It is actually not the same, that's why I was asking. If you check here: https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/keras/losses/categorical_crossentropy. y_true should be placed before y_pred.
