### ISSUE TITLE
where is implementation on partial backdoor attack?

### ISSUE THREAD

**Issue by Kataang** [bolunwang/backdoor#13]
Thank you for your work on backdoor attacks!
In your paper, you mentioned that you have conducted experiments on partial backdoor attack. I've also noticed that in issue "Adaptation for partial backdoor attack #9", someone succeeded in implementing partial backdoor attack.
However, I didn't figure out **where I can make partial backdoor attack settings, and where the codes are to implement partial backdoor attack.** In "gtsrb_injection_example.py", it looks like that you just choose pictures from arbitrary label (with injection ratio), and convert them to target label. **I couldn't found where I can mark source label.** Could you help me figure out where I can make this setting?
Thanks a lot!

**Comment by bolunwang** [comment]
Partial backdoor detection is implemented not by changing the code, but changing the input data. You can change the input image set by filter out things other than images from the source label of interest. The rest of the reverse engineering code could stay unchanged.
