### ISSUE TITLE
Is this detection method a white-box setting?

### ISSUE THREAD

**Issue by tonggege001** [bolunwang/backdoor#14]
Hello, I have learned your work on backdoor detection of neural network. I want to confirm if your method are under white-box condition(because the mask and reversed trigger generation require the gradient of the model). But there is a paper says that your method are under black-box condition (https://arxiv.org/pdf/2007.10760.pdf    Page. 22, Table II). I think the authors are wrong, what do you think?

**Comment by bolunwang** [comment]
Without too much context into the paper, I can't comment on whether authors are wrong or not. But I can try clarify our assumptions in Neural Cleanse. We design the system from the defender's perspective, meaning people owning the model trying to detect, analyze, and remove potential backdoors. This means the defender already has the model and a small clean dataset.

**Comment by tonggege001** [comment]
OK, thank you very much.
