### ISSUE TITLE
trigger pattern mentioned in the paper

### ISSUE THREAD

**Issue by jiashenC** [bolunwang/backdoor#3]
Hi,

Is the trigger pattern ∆ mentioned in the paper predefined?

**Comment by bolunwang** [comment]
Not exactly sure if I get the question...

If you are referring to how we initiate delta in the reverse engineering process, we use random values as start.

**Comment by jiashenC** [comment]
Thanks, that's what I refer to. I think I misunderstood the Reverse Engineering Process in the paper.
