### ISSUE TITLE
About data poisoning

### ISSUE THREAD

**Issue by tiroshenao** [bolunwang/backdoor#5]
Hello, this is a cool job. Recently I'm reading your paper. I'm wondering can you share the file to poison the clean dataset? It can be a great help to understand your paper. Thanks a lot.

**Comment by Shawn-Shan** [comment]
For the GTSRB model, the backdoor injection code is under the injection repo (https://github.com/bolunwang/backdoor/tree/master/injection). We shared the training data in a .h5 file on google drive. (https://drive.google.com/file/d/1kcveaJC3Ra-XDuaNqHzYeomMvU8d1npj/view?usp=sharing)
