### ISSUE TITLE
Adaptation for partial backdoor attack

### ISSUE THREAD

**Issue by Xavierxhq** [bolunwang/backdoor#9]
Your excellent works is much appreciated. However i have one small question to throw.
As mentioned in the paper, you have implemented detection for partial backdoor attack, may you share the code.
**My confusion is**, for each target label, if i try each source-target pairs, i may eventually get several reversed triggers for each target label. Still, i can find a subset of reversed triggers that are regarded as outlier (in the case, **for a target label, the number of reversed triggers is likely to be more than 1**). Then when i am doing detection, **the activation profile should be determined by which reversed trigger(s)?**
Thanks for your kindly reply!

**Comment by Xavierxhq** [comment]
i may have new understanding, once the model is considered poisoned, no matter compromised by complete/partial backdoor attack, the filter operation will be applied, therefore the activation profile is indeed unnecessary.

**Comment by bolunwang** [comment]
Sorry for the late reply. Haven't been checking github for quite a while.

Once we consider the partial backdoor setting, the goal is not to identify which target label is polluted, but which (source, target) pair is polluted.
